### ISSUE TITLE
Add clickable link

### ISSUE THREAD

**Issue by Hipska** [Glodenox/wme-road-events#22]
Just like OpenMaps has a link to GIPOD events, it would be nice that this plugin does/has that as well.

**Comment by Glodenox** [comment]
Are your referring to the link on the map layer pointing to the map as a whole with `http://www.geopunt.be/kaart?app=Hinder_in_kaart_app&extent=<left, bottom, right, top coordinates>` or the link in the results pointing to a specific report with `http://www.geopunt.be/kaart?app=Hinder_in_kaart_app&lang=nl&GIPODID=<GIPOD ID>`?

While it would be relatively easy to do so, the point of this userscript is to show that information within the WME instead of directing you away from the editor. Then again, I haven't really been supporting this script all too well, so it's not up to me to make this harder for people.

**Comment by Hipska** [comment]
Yes the second one. It sometimes reveals more/other info.

**Comment by Glodenox** [comment]
Added in version 1.7.2, alongside a small restyle of the event details panel
